# Generated by Django 4.2.13 on 2024-05-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('average_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('date_of_released', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('photo_of_product', models.ImageField(upload_to='uploads/product/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('city_town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('photo_of_user', models.ImageField(upload_to='uploads/user/')),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_rating', models.CharField(max_length=100)),
                ('the_review', models.CharField(max_length=1000)),
                ('date_of_post', models.DateField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.profile')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.product')),
            ],
        ),
    ]
